### ISSUE TITLE
Cannot retrieve certain /block/transaction hashes because of tx-tracer errors

### ISSUE THREAD

**Issue by henridevieux** [celo-org/rosetta#180]
### Description
For certain transaction hashes, the /block/transaction endpoint fails with a Kliento tracing error. Rosetta returns the following: 
```
{"code":502,"message":"Celo node rpc request failed","retriable":false,"details":{
"context":"can't run celo-rpc tx-tracer: Error: Unexpected stack height. Expected: 1 Actual: 3
Additional info:     in server-side tracer function 'result':TraceTransaction@
can't run celo-rpc tx-tracer: Error: Unexpected stack height. Expected: 1 Actual: 3 
Additional info:     in server-side tracer function 'result'"}}
```

An example of a specific block/transaction hash that triggers this error is: https://alfajores-blockscout.celo-testnet.org/tx/0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813/internal-transactions

### Steps to reproduce:
1. Running the latest version rosetta node on the **alfajores** network. (rosetta v0.8.5; celo-blockchain v1.3.2). It must be started with --rpc.reqTimeout 120s
2. Issue the following rpc to the node:
```
curl --request POST --url 'http://127.0.0.1:8080/block/transaction' --header 'Content-Type: application/json' --data-raw '{
    "network_identifier": {
        "blockchain": "celo",
        "network": "44787"
    },
    "block_identifier": {
        "index": 8681358,
        "hash": "0x90cb1b3b2f7c34aa14a11db2b2a13a9850cc4147f92468ed645355a4214c1aec"
    },
    "transaction_identifier": {
        "hash": "0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813"
    }
}'
```

### Expected Behavior:
Since the transaction [appears to be valid](https://alfajores-blockscout.celo-testnet.org/tx/0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813/internal-transactions), we expect to receive the transaction details as follows:
```
{"transaction":{"transaction_identifier":
{"hash":"0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813"},"operations":[
{"operation_identifier":{"index":0},"type":"fee","status":"success","account":{"address":"0x621843731fe33418007C06ee48CfD71e0ea828d9"},
"amount":
{"value":"7112293600000000","currency":{"symbol":"cGLD","decimals":18}}},{"operation_identifier":
{"index":1},"related_operations":[{"index":0}],"type":"fee","status":"success","account":{"address":"0xAA963FC97281d9632d96700aB62A4D1340F9a28a"},
"amount":{"value":"1778073400000000","currency":{"symbol":"cGLD","decimals":18}}},{"operation_identifier":{"index":2},"related_operations":[{"index":0},{"index":1}],"type":"fee","status":"success",
"account":{"address":"0xA4297364D76c45180b7783403d81C2992d9399d6"},"amount":{"value":"-8890367000000000","currency":{"symbol":"cGLD","decimals":18}}}]}}
```
Instead, rosetta returns the following error: `can't run celo-rpc tx-tracer: Error: Unexpected stack height. Expected: 1 Actual: 3 Additional info:     in server-side tracer function 'result':TraceTransaction`.

### Additional Information:
Removing the [tx-tracing code ](https://github.com/celo-org/rosetta/blob/master/analyzer/txtracer.go#L158) allows this request to return the transaction details successfully.

**Comment by henridevieux** [comment]
@piersy Rosetta currently uses [celo-blockchain v1.3.2](https://github.com/celo-org/rosetta/blob/master/go.mod#L8). If you confirm it can support celo-blockchain v1.5, I can test whether this issue still exists in 1.5.

**Comment by piersy** [comment]
Hi @henridevieux  Rosetta would need to be modified to use v1.5. I don't think changing the version of the blockchain dependency for Rosetta would help though.

My understanding is that Rosetta makes use of Kliento which has a custom tracer defined in it to extract the details of celo gold transfers. The tracer is a bit of javascript that is then passed as an argument to the debug_traceTransaction rpc endpoint of a node running on alfajores.

Tracer javascript: https://github.com/celo-org/kliento/blob/37af78cb0d3faf6b760d1d1b110d45516ae6716a/client/debug/tracer.go#L30

So I think either there is a problem with the javascript code of the tracer, or there is something wrong in the way that the node is processing the tracer.

Do you know if you were you previously able to process this same transaction without any problems? (If so it points to there being a problem with the most recent alfajores node update)

**Comment by henridevieux** [comment]
@piersy Makes sense, thanks. 

No, we were never able to process that transaction. Our internal syncing services stopped when they hit that block for the first time.

**Comment by piersy** [comment]
@henridevieux Thanks for the update!

So I'm suspecting there is a problem with the tracer javascript code, the stack structure it maintains seems to get out of sync with the EVM's internal execution depth.

**Comment by piersy** [comment]
Hi @henridevieux, I think I've found the issue here. I was able to successfully trace that transaction by increasing the timeout provided when calling debug.TraceTransaction.

I was executing the tracer directly from the geth console, below you can see 2 attempts, the first without a timeout set which is failing and the second with the timeout set to `120s` which is passing.

```
Welcome to the Celo JavaScript console!

instance: celo/v1.5.0-stable/linux-amd64/go1.16.13
at block: 9415729 (Mon Jan 17 2022 16:08:54 GMT+0000 (WET))
 modules: debug:1.0 eth:1.0 net:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d
> loadScript("./tracing_investigation/processed_tracer.js");  debug.traceTransaction("0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813", {tracer: tracer})
Error: Error: Unexpected stack height. Expected: 1 Actual: 3 Additional info:     in server-side tracer function 'result'
	at web3.js:6357:37(47)
	at web3.js:5091:62(37)
	at <eval>:1:83(11)

> loadScript("./tracing_investigation/processed_tracer.js");  debug.traceTransaction("0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813", {tracer: tracer, timeout:"120s"})
{
  block: 8681358,
  from: "0xa4297364d76c45180b7783403d81c2992d9399d6",
  gas: "0x1284f98",
  gasUsed: "0x1067296",
  time: "49.982793847s",
  to: "0xb43326b345e9c956e66d12f1b927aec0a57dd4d1",
  transfers: [],
  type: "CALL",
  value: "0x0"
}
>
```

If you look into the kliento code you can see that the timeout is hardcoded to `50s`.

So an immediate workaround for you would be to modify the kilento code to have a higher timeout.

I'm going to continue to investigate why the error returned does not mention the timeout and think about how best to solve this.

**Comment by henridevieux** [comment]
@piersy Thanks for the details.

Is it expected that this (or any other) transactions may take >50s to Trace, or is the tracing code problematic? I want to make sure that timeouts are set appropriately for services that make requests to celo-rosetta.

We will look into patching the Kliento code to provide a temporary workaround for this issue. In the meantime, I will keep an eye out for outcomes of your investigation.

**Comment by piersy** [comment]
Hi @henridevieux 

I have submitted a pr to rosetta #181 that makes the tracing calls use the configured rpc request timeout. Please take a look and see if that would work well for you, that should alleviate any need for you to patch kliento.

>Is it expected that this (or any other) transactions may take >50s to Trace, or is the tracing code problematic? I want to make sure that timeouts are set appropriately for services that make requests to celo-rosetta.

It is expected that tracing could take that long or longer. There doesn't seem to be anything wrong with the tracing code although it could probably be made faster.  I suspect one of the reasons tracing is so slow is that the blockchain node is interpreting the javascript tracer using an embedded javascript vm and makes a call to it through C bindings for each EVM operation. For the transaction in question there were over 4 million evm operations.

The time to trace I think could be roughly determined by, the tx(how much it does), the tracer(how much that does) and the specs of the blockchain node that the `debug_TraceTransaction` call is made to.

I guess we can roughly measure how much a tx does by its gas usage, [this](https://alfajores-blockscout.celo-testnet.org/tx/0x0c6893c36b3dc2b28fbe9958aa72913badc9701ce7f28871b9ba96daee53b813/internal-transactions) one used a lot `17,780,734` out of the block total of `20,000,000`.

The code of the tracer is fixed, unless someone updates it in kliento. 

So In my testing on a 2 core 4GiB ram machine the trace of that tx took roughly 50s (+- ~5s), so we could predict that tracing the largest possible tx on that machine would take `(20,000,000/17,780,734) * 50s = 56.24s`. So as a reasonable starting timeout for that machine I would go for say 70s to account for random fluctuations and the fact that the machine may be doing something else at the same time.

**Comment by henridevieux** [comment]
@piersy Great - thanks for the updates. It looks like the commit and PR you linked here should fix the issues we are seeing. I'll watch for when you merge it and run our tests shortly thereafter.
